---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  selector:
    name: poi
  #clusterIP: None
  ports:
  - name: poi
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: tripinsights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripinsights
  template:
    metadata:
      labels:
        app: tripinsights
    spec:   
      containers:
      - name: poi
      image: registryzwh7849.azurecr.io/poi:1.0
      env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
            name: db-secret
            key: password
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
     