---
apiVersion: v1
kind: Pod
metadata:
  name: poi-pod
  labels:
    app: poi
spec:
  #replicas: 3
  containers:
  - name: poi
    image: registryzwh7849.azurecr.io/poi:1.0
    env:
      - name: SQL_USER
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: username
        #value: "sqladminzWh7849"
      - name: SQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: password
        #value:  "cY0vi8Ws6"
      - name: SQL_SERVER
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: host
        #value: "sqlserverzwh7849.database.windows.net"