---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  selector:
    app: poi
  #clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:   
      containers:
      - name: poi
        image: registryzwh7849.azurecr.io/poi:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
     