---
apiVersion: v1
kind: Pod
metadata:
  name: poi-pod
  labels:
    app: poi
spec:
  #replicas: 3
  containers:
  - name: poi
    image: registryzwh7849.azurecr.io/poi:1.0
    env:
      - name: ENV_SQL_USER
        value: "sqlserverzwh7849"
      - name: SQL_PASSWORD
        value:  "sqladminzWh7849"
      - name: SQL_SERVER
        value: "cY0vi8Ws6"