# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: t4-msopenhack-keyvault       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: db-secret-hostname
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: db-secret-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-secret-password
          objectType: secret
          objectVersion: ""
    tenantId: d20cffdf-bc85-4dba-8b42-adc0047ee93b                # The tenant ID of the key vault