---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  selector:
    name: userprofile
  #clusterIP: None
  ports:
  - name: userprofile
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  selector:
    name: trips
  #clusterIP: None
  ports:
  - name: trips
    port: 80
    targetPort: 80
    protocol: TCP