apiVersion: v1
kind: Pod
metadata:
  name: trips-pod
  labels:
    app: trips
spec:
  #replicas: 3
  containers:
    - name: trips
      image: registryzwh7849.azurecr.io/trips:1.0
      ports:
        - containerPort: 80
      env:
        - name: PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
        - name: SQL_USER
          value: "sqladminzWh7849"
        - name: SQL_PASSWORD
          value: "cY0vi8Ws6"
        - name: SQL_SERVER
          value: "sqlserverzwh7849.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: OPENAPI_DOCS_URI
          value: "http://trips-pod"
        - name: DEBUG_LOGGING
          value: "false"