---
apiVersion: v1
kind: Pod
metadata:
  name: tripviewer-pod
  labels:
    app: trips
spec:
  #replicas: 3
  containers:
  - name: tripviewer
    image: registryzwh7849.azurecr.io/tripviewer:1.0
    env:
      - name: TRIPS_API_ENDPOINT
        value: "http://endpoint"
      - name: USERPROFILE_API_ENDPOINT
        value: "http://endpoint"


