---
apiVersion: v1
kind: Pod
metadata:
  name: userprofile-pod
  labels:
    app: userprofile
spec:
  #replicas: 3
  containers:
  - name: userprofile
    image: registryzwh7849.azurecr.io/userprofile:1.0