---
apiVersion: v1
kind: Service
metadata:
  name: userjava
  namespace: api
spec:
  selector:
    app: userjava
  #clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-deployment
  namespace: api
  labels:
    app: userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
        - name: userjava
          image: registryzwh7849.azurecr.io/userjava:1.0
          env:
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: db-secret-hostname
                  key: secret
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret-username
                  key: secret
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-password
                  key: secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
              name: userjava
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-podid"
